version: '3.8'

services:
  db:
    image: postgres:15
    container_name: questplanner-db
    restart: always
    environment:
      POSTGRES_DB: questplanner_db
      POSTGRES_USER: quest_user
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: questplanner-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
